# Site wide configuration

title: J. McCartin
locale: en_US
description: Former urban planner etc.
logo: 
search: true
url: http://www.mccartin.info

# Jekyll configuration

permalink:   /:categories/:title/


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: June McCartin
  email: mccartinjune@gmail.com
